### ISSUE TITLE
Clear Reference After Takeoff

### ISSUE THREAD

**Issue by Ian0526** [thisMicki/BrackenFavRoom#1]
Null the gameObject's reference after the ship has left. Tile SmallRoom2 doesn't spawn on every map and this will cause issues if the plugin identifies the tile during an earlier round, but in the next consecutive round that it doesn't spawn in, the reference will have no real position.

Example of how you can do it:
https://github.com/Ian0526/SnatchinBracken/blob/main/Patches/ship/StartOfRoundPatch.cs

**Comment by thatCleo** [comment]
Thanks for informing me about this possible issue. I tested if it was necessary but the reference only exists within the EnemyAI class. Due to all Enemies being destroyed at the end of a round, there is no need for the SmallRoom2 reference to be set to null, since it doesn't exist anymore. This means that if the SmallRoom2 tile doesn't spawn in a following round, the GameObject.Find() will just set the new reference to null and the favorite position will not be changed.

**Comment by Ian0526** [comment]
Your fix works, and setting it to null is still crucial because that field will retain the value it's assigned regardless if its initial reference is set to null. Even if the EnemyAI is destroyed, that reference will still exist. Think of it as a copy

**Comment by thatCleo** [comment]
I'm sorry, but I currently don't understand what you mean.
As of right now, when ever a Flowerman spawns the smallroom reference is first defined in the start function of that Flowerman. If the SmallRoom2 tile exists, the reference gets the GameObject assigned, otherwise it is set to null, regardless of if a round has been played before or not. As soon as the Flowerman Object gets destroyed, there is nothing that I could set to null, since the reference variable doesn't exist outside of the Flowerman.

**Comment by Ian0526** [comment]
You're good, that works
